version: "3.9"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  geth:
    container_name: geth
    image: ethereum/client-go:latest
    restart: always
    entrypoint: "/bin/sh /entrypoint.sh"
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    volumes:
      - /data/geth:/data
      - ./keys/jwt-secret.txt:/config/jwt-secret.txt
      - ./scripts/run_geth.sh:/entrypoint.sh
    <<: *logging

  beacon:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    restart: always
    depends_on:
      - geth
      - create-beacon-chain-genesis
    command:
      - --sepolia
      - --accept-terms-of-use
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --genesis-state=/genesis/genesis.ssz
      - --jwt-secret=/config/jwt-secret.txt
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
    volumes:
      - /data/beacon:/data
      - ./genesis/genesis.ssz:/genesis/genesis.ssz
      - ./keys/jwt-secret.txt:/config/jwt-secret.txt
    <<: *logging
